name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ros:foxy

    steps:

      # Check out repo
      - uses: actions/checkout@v2

      # Setup ROS2 system deps
      - uses: ros-tooling/setup-ros@0.0.25

      - name: Change dir to ROS2 workspace
        run: cd tr_ws

      - name: Install deps with rosdep
        run: rosdep install -i --from-path src --rosdistro foxy -y
          

      - name: Build with colcon
        run: colcon build

      - name: Source local install
        run: source install/setup.bash

