name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    # container: ros:foxy

    steps:

      - name: Check out repo
        uses: actions/checkout@v2

      - name: Setup ROS2 system deps and distro
        uses: ros-tooling/setup-ros@0.0.25
        with: 
          required-ros-distributions: foxy

      - name: Install deps with rosdep
        run: |
          cd tr_ws
          rosdep update
          rosdep install -i --from-path src --rosdistro foxy -y
          
      - name: Build with colcon
        run: colcon build

      - name: Source local install
        run: source install/setup.bash

