name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    # container: ros:foxy

    steps:

      - name: Check out repo
        uses: actions/checkout@v2


