name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ros:foxy

    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Change dir to ROS2 workspace
        run: cd tr_ws

      - name: Install deps with rosdep
        run: |
          sudo apt install python3-rosdep2
          rosdep update
          rosdep install -i --from-path src --rosdistro foxy -y

      - name: Build with colcon
        run: |
          sudo apt install python3-colcon-common-extensions
          colcon build

      - name: Source local install
        run: source install/setup.bash

